opt_type: "sv3d_24"

optimizer:
  name: "adamw"
  lr: 0.000002
  betas:
    - 0.9
    - 0.999
  weight_decay: 0.01

lr_scheduler:
  name: "one_cycle"
  max_lr: ${optimizer.lr}
  pct_start: 0.001

train:
  batch_size_per_gpu: 1
  epochs: 30000
  log_freq: 1
  early_eval_freq: 200
  eval_freq: 1000
  save_freq: 2000
  ema_kwargs:
    decay: 0.9999
    use_ema_warmup: false
    inv_gamma: 1.
    power: 0.75

val:
  batch_size_per_gpu: 2
